services:
  backend:
    build:
      context: ./backend
    command: tail -f /dev/null
    ports:
      - 8080:3000
    volumes:
      - ./backend:/app/

  terragrunt:
    build:
      context: ./infrastructure/
    environment:
      AWS_PROFILE: personal-account
    volumes:
      - ./infrastructure:/workspace
      - ~/.aws/:/root/.aws
    command: tail -f /dev/null
